spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9094
      - localhost:9096

    producer:
      retries: 3
      acks: all             # 强一致性
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: cache-delete-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.z.sharding.pojo
  configuration:
    map-underscore-to-camel-case: true
