spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.z.sharding.pojo
  configuration:
    map-underscore-to-camel-case: true