version: '3.8'

services:
  mysql-master:
    image: mysql:9.3.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: z7763882336
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    volumes:
      - master-data:/var/lib/mysql

  mysql-slave1:
    image: mysql:9.3.0
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: z7763882336
    ports:
      - "3307:3306"
    command: >
      --server-id=2
      --relay-log=relay-bin
      --log-bin=mysql-bin
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    depends_on:
      - mysql-master
    volumes:
      - slave1-data:/var/lib/mysql

  mysql-slave2:
    image: mysql:9.3.0
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: z7763882336
    ports:
      - "3308:3306"
    command: >
      --server-id=3
      --relay-log=relay-bin
      --log-bin=mysql-bin
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    depends_on:
      - mysql-master
    volumes:
      - slave2-data:/var/lib/mysql

volumes:
  master-data:
  slave1-data:
  slave2-data:

